name = "rolldorado-casino-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-casino.com.de"
HMAC_KEY = "489464c96ab0329ffbd16be145fe71675115ee03c1a9ed04df79e71356694af8"
COOKIE_NAME = "2ua"
PLAY_PATH = "play"
BUTTON_ID = "pdcf75a892dccbb7b254a9bca7dc2ed0e"
GATE_SALT = "e148b6013fe1ee90"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "sx2r"
CTA_SELECTOR = ".play-button"
